/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { MeshDistortMaterial, MeshWobbleMaterial, useGLTF } from '@react-three/drei'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    l_handMeshNode: THREE.SkinnedMesh
    b_l_wrist: THREE.Bone
    b_l_thumb0: THREE.Bone
    b_l_thumb1: THREE.Bone
    b_l_thumb2: THREE.Bone
    b_l_thumb3: THREE.Bone
    b_l_thumb_null: THREE.Bone
    b_l_index1: THREE.Bone
    b_l_index2: THREE.Bone
    b_l_index3: THREE.Bone
    b_l_index_null: THREE.Bone
    b_l_middle1: THREE.Bone
    b_l_middle2: THREE.Bone
    b_l_middle3: THREE.Bone
    b_l_middle_null: THREE.Bone
    b_l_ring1: THREE.Bone
    b_l_ring2: THREE.Bone
    b_l_ring3: THREE.Bone
    b_l_ring_null: THREE.Bone
    b_l_pinky0: THREE.Bone
    b_l_pinky1: THREE.Bone
    b_l_pinky2: THREE.Bone
    b_l_pinky3: THREE.Bone
    b_l_pinky_null: THREE.Bone
    b_l_forearm_stub: THREE.Bone
  }
  materials: {
    ['lambert2.001']: THREE.MeshStandardMaterial
  }
}

export function OculusHandLeft(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/OculusHand_L.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.b_l_wrist} />
        <primitive object={nodes.b_l_thumb0} />
        <primitive object={nodes.b_l_thumb1} />
        <primitive object={nodes.b_l_thumb2} />
        <primitive object={nodes.b_l_thumb3} />
        <primitive object={nodes.b_l_thumb_null} />
        <primitive object={nodes.b_l_index1} />
        <primitive object={nodes.b_l_index2} />
        <primitive object={nodes.b_l_index3} />
        <primitive object={nodes.b_l_index_null} />
        <primitive object={nodes.b_l_middle1} />
        <primitive object={nodes.b_l_middle2} />
        <primitive object={nodes.b_l_middle3} />
        <primitive object={nodes.b_l_middle_null} />
        <primitive object={nodes.b_l_ring1} />
        <primitive object={nodes.b_l_ring2} />
        <primitive object={nodes.b_l_ring3} />
        <primitive object={nodes.b_l_ring_null} />
        <primitive object={nodes.b_l_pinky0} />
        <primitive object={nodes.b_l_pinky1} />
        <primitive object={nodes.b_l_pinky2} />
        <primitive object={nodes.b_l_pinky3} />
        <primitive object={nodes.b_l_pinky_null} />
        <primitive object={nodes.b_l_forearm_stub} />
        <skinnedMesh
          geometry={nodes.l_handMeshNode.geometry}
          skeleton={nodes.l_handMeshNode.skeleton}
          material={materials['lambert2.001']}
          material-skinning={true}
          frustumCulled={false}
          receiveShadow={true}
          castShadow={true}
        >
          {/* <MeshDistortMaterial color='blue' skinning={true} distort={1} speed={0.2}/> */}
          {/* {props.children} */}
        </skinnedMesh>
    </group>
  )
}

useGLTF.preload('/models/OculusHand_L.glb')
